apiVersion: v1
data:
  index.html: |
    <img src="https://media.giphy.com/media/hEc4k5pN17GZq/giphy.gif" alt="wat"  width="1000" />
kind: ConfigMap
metadata:
  creationTimestamp: "2021-06-07T15:41:34Z"
  name: travolta
  namespace: default
  resourceVersion: "10595"
  uid: b434d6e1-8b38-4d4b-a8fa-3795c582e752
