---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: confused-travolta
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: confused-travolta
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: confused-travolta
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: confused-travolta
        ports:
        - containerPort: 80
        volumeMounts:
        - name: index
          mountPath: /usr/share/nginx/html
      nodeSelector:
        type: chonky
      volumes:
      - name: index
        configMap:
          name: travolta
---
apiVersion: v1
kind: Service
metadata:
  name: confused-travolta
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app.kubernetes.io/name: confused-travolta
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-travolta
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/security-groups: {{.Values.albSecurityGroup}}
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: confused-travolta
              servicePort: 80
---
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: allow-alb-access
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: confused-travolta
  securityGroups:
    groupIds:
      - {{.Values.podSecurityGroup}}
---
apiVersion: v1
data:
  index.html: |
    <img src="https://media.giphy.com/media/hEc4k5pN17GZq/giphy.gif" alt="wat"  width="1000" />
kind: ConfigMap
metadata:
  name: travolta